package com.example.api

import com.example.BuildConfig
import com.squareup.moshi.Moshi
import com.squareup.moshi.kotlin.reflect.KotlinJsonAdapterFactory
import okhttp3.MediaType.Companion.toMediaType
import okhttp3.OkHttpClient
import okhttp3.Request
import okhttp3.RequestBody.Companion.toRequestBody
import kotlinx.coroutines.Dispatchers
import kotlinx.coroutines.withContext
import org.json.JSONArray
import org.json.JSONObject

object GeminiClient {
    private const val BASE_URL = "https://generativelanguage.googleapis.com/v1beta/models/gemini-3.5-flash:generateContent"
    
    private val client = OkHttpClient.Builder()
        .connectTimeout(60, java.util.concurrent.TimeUnit.SECONDS)
        .readTimeout(60, java.util.concurrent.TimeUnit.SECONDS)
        .writeTimeout(60, java.util.concurrent.TimeUnit.SECONDS)
        .build()

    suspend fun generateContent(prompt: String, systemInstruction: String? = null): String = withContext(Dispatchers.IO) {
        val apiKey = BuildConfig.GEMINI_API_KEY
        if (apiKey.isEmpty() || apiKey == "MY_GEMINI_API_KEY") {
            return@withContext "Error: Gemini API Key is missing. Please configure it in your Secrets Panel in AI Studio."
        }

        try {
            // Build Gemini JSON request manually to avoid serialization overhead and ensure extreme resilience
            val requestJson = JSONObject()
            
            // System instruction
            if (systemInstruction != null) {
                requestJson.put("systemInstruction", JSONObject().put("parts", JSONArray().put(JSONObject().put("text", systemInstruction))))
            }

            // Contents
            val part = JSONObject().put("text", prompt)
            val content = JSONObject().put("parts", JSONArray().put(part))
            requestJson.put("contents", JSONArray().put(content))

            val mediaType = "application/json; charset=utf-8".toMediaType()
            val requestBody = requestJson.toString().toRequestBody(mediaType)

            val request = Request.Builder()
                .url("$BASE_URL?key=$apiKey")
                .post(requestBody)
                .build()

            client.newCall(request).execute().use { response ->
                if (!response.isSuccessful) {
                    return@withContext "API Call Failed: ${response.code} ${response.message}"
                }
                val bodyString = response.body?.string() ?: return@withContext "Error: Empty response body"
                
                val jsonResponse = JSONObject(bodyString)
                val candidates = jsonResponse.optJSONArray("candidates")
                if (candidates != null && candidates.length() > 0) {
                    val firstCandidate = candidates.getJSONObject(0)
                    val contentObj = firstCandidate.optJSONObject("content")
                    if (contentObj != null) {
                        val parts = contentObj.optJSONArray("parts")
                        if (parts != null && parts.length() > 0) {
                            return@withContext parts.getJSONObject(0).optString("text", "No text generated.")
                        }
                    }
                }
                "No valid answer was generated by the model."
            }
        } catch (e: Exception) {
            "Network / API Error: ${e.localizedMessage ?: e.message}"
        }
    }

    suspend fun solveDoubt(doubt: String, course: String): String {
        val sysInstruction = "You are an expert tutor at Rama Technical Institute. Solve the student's doubt clearly, comprehensively, and in detail. Use Indian English or simple Hindi-English where appropriate. Course: $course"
        return generateContent(doubt, sysInstruction)
    }

    suspend fun generateHomework(topic: String, course: String): String {
        val sysInstruction = "You are an expert teacher at Rama Technical Institute. Generate a professional homework assignment, complete with Title, Description, Learning Objectives, and 5 detailed questions/tasks. Course: $course"
        val prompt = "Generate a homework assignment about: $topic"
        return generateContent(prompt, sysInstruction)
    }

    suspend fun generateQuestionPaper(subject: String, course: String): String {
        val sysInstruction = "You are a senior examiner at Rama Technical Institute. Generate a comprehensive and professional exam paper of 50 marks. Section A: 5 MCQ (1 mark each), Section B: 5 Short questions (5 marks each), Section C: 2 long questions (10 marks each). Subject: $subject, Course: $course"
        val prompt = "Create a question paper for subject: $subject"
        return generateContent(prompt, sysInstruction)
    }

    suspend fun analyzePerformance(resultsJson: String, attendanceRate: Double): String {
        val sysInstruction = "You are an academic mentor at Rama Technical Institute. Analyze the student's performance report, pointing out strengths, weaknesses, and a concrete action plan for improvement."
        val prompt = "Student Academic Record:\n$resultsJson\nAttendance Rate: $attendanceRate%\nAnalyze this report and provide custom mentoring advice."
        return generateContent(prompt, sysInstruction)
    }
}
